services:
  - type: web
    name: lavalust-krystal
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        sync: false
      - key: DB_HOST
        value: mysql-1d8a6099-lavalust-fabic-0b88.a.aivencloud.com
      - key: DB_PORT
        value: "19881"
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false